# Generated by Django 3.1.3 on 2020-11-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist_songs',
            old_name='songs',
            new_name='song',
        ),
    ]
