# Generated by Django 5.0.4 on 2024-05-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0003_auto_20201102_1932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="playlist_songs",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
