# Generated by Django 3.1.1 on 2020-09-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_songs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('storage_name', models.CharField(max_length=100)),
                ('mood', models.CharField(choices=[('sad', 'sad'), ('happy', 'happy'), ('normal', 'normal')], default='normal', max_length=50)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='songs.playlist')),
            ],
        ),
    ]
