# Generated by Django 3.1 on 2020-09-16 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='playlist_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='mood',
            new_name='emotion',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='song_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='storage_name',
            new_name='song_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
