# Generated by Django 3.1.3 on 2020-11-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200916_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
