# Generated by Django 3.1.3 on 2020-11-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_delete_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_url',
            field=models.CharField(max_length=400),
        ),
    ]
