# Generated by Django 5.0.4 on 2024-05-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0004_auto_20201103_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
